version: '3.9'

networks:
  test-network:

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    networks:
      - test-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", 'redis-cli', 'ping']
      start_period: 20s
      timeout: 20s
      retries: 10
  db:
    image: 'percona:8.0'
    container_name: 'db'
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: always
    networks:
      - test-network
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --default-authentication-plugin=mysql_native_password 
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', root' ]
      start_period: 20s
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'app'
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/app
    networks:
      - test-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy