version: '3.9'

networks:
  test-network:

services:
  db:
    image: 'percona:8.0'
    container_name: 'db'
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: always
    networks:
      - test-network
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --default-authentication-plugin=mysql_native_password 
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'app'
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/app
    networks:
      - test-network
    depends_on:
      db:
        condition: service_started